
SELECT MASTER_CUSTOMER.NAMA_CUSTOMER, TRANSAKSI_HEADER.KODE_TRANSAKSI, MASTER_BARANG.NAMA_BARANG,TRANSAKSI_DETAIL.QTY
FROM MASTER_CUSTOMER
INNER JOIN TRANSAKSI_HEADER ON MASTER_CUSTOMER.CUSTOMER_ID = TRANSAKSI_HEADER.CUSTOMER_ID
INNER JOIN TRANSAKSI_DETAIL ON TRANSAKSI_HEADER.KODE_TRANSAKSI = TRANSAKSI_DETAIL.KODE_TRANSAKSI
INNER JOIN MASTER_BARANG ON TRANSAKSI_DETAIL.KODE_BARANG = MASTER_BARANG.KODE_BARANG
